allowBuilds:
  '@scarf/scarf': false
  better-sqlite3: true
  esbuild: true
  sqlite3: true
minimumReleaseAgeExclude:
  - '@mikro-orm/core@7.2.2'
  - '@mikro-orm/postgresql@7.2.2'
  - '@mikro-orm/sql@7.2.2'
  - '@mikro-orm/sqlite@7.2.2'
  - '@nestjs/common@12.1.1'
  - '@nestjs/platform-express@12.1.1'
  - '@nestjs/testing@12.1.1'
